### ISSUE TITLE
Trinidad Bi-fold

### ISSUE THREAD

**Issue by pyklstudios** [nupykl/pykl-todo#16]

**Comment by kevinduffy** [comment]
Waiting for Final revisions

**Comment by kevinduffy** [comment]
Final Copy to finish on Monday 3/2

**Comment by kevinduffy** [comment]
![chicagomsdc-logo_primary 2](https://cloud.githubusercontent.com/assets/8546021/6465206/8e0b9a78-c18d-11e4-9d60-704404b42def.jpg)

**Comment by kevinduffy** [comment]
Brochures ordered
